[package]
name = "cbindgen"
version = "0.8.0"
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>",
           "Kartikaya Gupta <kats@mozilla.com>",
           "Ryan Hunt <rhunt@eqrion.net>"]
license = "MPL-2.0"
description = "A tool for generating C bindings to Rust code."
keywords = ["bindings", "ffi", "code-generation"]
categories = ["external-ffi-bindings", "development-tools::ffi"]
repository = "https://github.com/eqrion/cbindgen/"

[badges]
travis-ci = { repository = "eqrion/cbindgen" }

[dependencies]
clap = "2"
log = "0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_derive = "1.0"
tempfile = "3.0"
toml = "0.4"

[dependencies.syn]
version = "0.15.0"
default-features = false
features = ["clone-impls", "derive", "extra-traits", "full", "parsing", "printing"]

[[bin]]
name = "cbindgen"
path = "src/main.rs"
doc = false

[lib]
name = "cbindgen"
path = "src/lib.rs"
