[package]
name = "cbindgen"
version = "0.1.27"
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>",
           "Kartikaya Gupta <kats@mozilla.com>",
           "Ryan Hunt <rhunt@eqrion.net>"]
license = "MPL-2.0"
description = "A tool for generating C bindings to Rust code."
keywords = ["bindings", "ffi", "code-generation"]
categories = ["external-ffi-bindings", "development-tools::ffi"]
repository = "https://github.com/eqrion/cbindgen/"
exclude = ["test.py", "compile-tests/**"]

[badges]
travis-ci = { repository = "eqrion/cbindgen" }

[dependencies]
clap = "2"
log = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
tempdir = "0.3"
toml = "0.3"

[dependencies.syn]
version = "0.11"
features = ["full"]

[[bin]]
name = "cbindgen"
path = "src/main.rs"
doc = false

[lib]
name = "cbindgen"
path = "src/lib.rs"
