[package]
name = "cbindgen-macro"
version = "0.1.0"
edition = "2021"
description = "Procedural macro attributes for cbindgen"
license = "MPL-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1"
syn = { version = "2.0", features = ["full"] }
